apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: springboot-ocp-app
  name: springboot-ocp-app
  selfLink: /api/v1/namespaces/my-sb-app/services/springboot-ocp-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    app: springboot-ocp-app
    deploymentconfig: springboot-ocp-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}