apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: springboot-ocp-app
  name: springboot-ocp-app
  selfLink: /apis/build.openshift.io/v1/namespaces/my-sb-app/buildconfigs/springboot-ocp-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: springboot-ocp-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/zolinz/spring-boot-ocp.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/openjdk18-openshift:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: 8PVHiirhGyBq0eOebM4G
      type: GitHub
    - generic:
        secret: M829UwYBotnqvwtoWcG3
      type: Generic
    - type: ConfigChange
status:
  lastVersion: 1